[versions]
kotlin = "2.1.10"
openapi-generator = "7.12.0"
jackson = "2.18.3"
kotlinx-datetime = "0.6.2"
coroutines = "1.9.0"
jUnitJupiterVersion = "5.13.4"
junitPlatformLauncher = "1.9.1"
ktor = "3.2.3"
logback = "1.5.3"

[libraries]
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version = "0.23.2" }
uuid = "com.benasher44:uuid:0.8.4"

# ktor
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-resources = { module = "io.ktor:ktor-server-resources", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-client-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-jackson = { module = "io.ktor:ktor-serialization-jackson", version.ref = "ktor" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
ktor-server-headers-response = { module = "io.ktor:ktor-server-auto-head-response", version.ref = "ktor" }
ktor-server-headers-caching = { module = "io.ktor:ktor-server-caching-headers", version.ref = "ktor" }
ktor-server-headers-default = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }

# Logging
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-logstash = { module = "net.logstash.logback:logstash-logback-encoder", version = "7.4" }
logger-fluentd = { module = "org.fluentd:fluent-logger", version = "0.3.4" }
logback-appenders = { module = "com.sndyuk:logback-more-appenders", version = "1.8.8" }

#kafka
kafka-client = { module = "org.apache.kafka:kafka-clients", version = "3.7.0" }

#Database
db-cache4k = "io.github.reactivecircus.cache4k:cache4k:0.13.0"

#Testing
jUnit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jUnitJupiterVersion" }
jUnit-engine = {module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jUnitJupiterVersion" }
jUnit-platform = {module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatformLauncher" }

[plugins]



