ktor:
    development: true
    application:
        modules:
            - "ru.otus.otuskotlin.postcardshop.ktor.ApplicationKt.module"
    deployment:
        port: 8080
    match:
        - classes
        - resources

    logger: logback

postcardshop:
    repository:
        test: "inmemory"
        prod: "$DB_TYPE_PROD:inmemory"

        psql:
            schema: public
            database: "$POSTSHOP_DB:postcardshop"
            host: "$POSTSHOP_HOST:localhost"
            port: "$POSTSHOP_PORT:5432"
            user: "$POSTSHOP_USER:postgres"
            password: "$POSTSHOP_PASS:postgres"

aaa: inmemory2"